### ISSUE TITLE
Blurry Skies

### ISSUE THREAD

**Issue by Neptium** [Abastro/StellarSky#69] opened 2016-06-30 13:23 UTC
The Sky in v0.1.5.0 of Stellar Sky (for Minecraft 1.7.10) and above has an issue of where the sky becomes "blurry" the stars and galaxy would seem like it's out of focused. v0.1.5.7 of Stellar Sky still has this problem with v0.1.3.8 of Stellar API
The [Sky ](http://imgur.com/JdC91UP)in the latest version.
The [Sky](http://imgur.com/zNTkldZ) in v0.1.4.8c and below.
If compared, the stars in v0.1.4.8c are much more "detailed" and "sharp".
The issue also affects the latest beta version(Stellar Sky v0.4.5.2.3) of 1.9.4-- didn't test for 1.8 Minecraft versions.

For all of these, I used the latest Stellar API and used the recommended version of forge for both 1.7.10 and 1.9.4
EDIT: Tested in 1.10.2 and the same problem is appearing (Stellar Sky v0.5.5.1.3 and Stellar API v0.5.4.1.1)

**Comment by Abastro** [comment] 2016-06-30 15:01
Change Brightness Contranst settings to smaller value.

**Comment by Abastro** [comment] 2016-06-30 15:30
Sorry, I might misunderstand what you mean. Did you mean that the individual stars are too fuzzy?

**Comment by PitchBright** [comment] 2016-06-30 15:38
@Neptium Now that I'm looking even more closely...  This is weird... when I look at my screenshots from v0.1.22 (which predates your v0.1.4.7)... my stars look blurrier than the imgur pic you posted of your v0.1.4.8c and below.

Can you download this zip of jpgs and take a look through them, and see if you would say that you consider the stars to be blurry (like you're concerned about currently)... or if they are sharp the way you have them in your 0.1.4.8c and earlier?

https://www.dropbox.com/s/3aroh2y0vnpp3vk/StellarSky.zip?dl=1

**Comment by PitchBright** [comment] 2016-06-30 15:56
Also @Neptium while you're at it... can you pastebin your config file for each version? A sharp version and a blurry version would be perfect, thanks!

**Comment by Abastro** [comment] 2016-06-30 16:09
@Neptium, Note that Stellar Sky v0.1.4.8c does not work well with Stellar API v0.1.3.8, since it was supposed to work with Stellar API v0.1.3.5b.
So apparently, the sharper version was malfunctioning.

**Comment by Neptium** [comment] 2016-06-30 16:16
The configs were set to default, didn't change anything (and I mean anything)

**Comment by PitchBright** [comment] 2016-06-30 16:18
@Neptium  Yeah, we were just curious as to what the values were set at (regardless of if you modified them)

That said, I think Abastro figured out the problem. An incompatibility between the API version and the mod version. Check his response on the forums. I think you can close the issue here, if I'm not mistaken.

**Comment by Neptium** [comment] 2016-06-30 16:25
But the 1.10 version still has this "issue". Also I would like to note that when I use 1.9.4 latest beta version of both, the API and Stellar Sky it has this issue but when using the recommended versions it's fine. The photos look pretty "out of focused" I mean I might be wrong but could you try to install the version I mention above and see if it appears on your computer(s)?

**Comment by Abastro** [comment] 2016-06-30 16:28
@Neptium I already tried that, you should have installed Stellar API v0.1.3.5b for Stellar Sky v0.1.4.8c.
So what you thought is correct is, actually malfunctioning and bugged out.

**Comment by PitchBright** [comment] 2016-06-30 16:28
Sorry... I meant to clarify... that the sharper stars are actually the problem... not the blurry ones.

**Comment by Neptium** [comment] 2016-06-30 16:32
I'll try to use the recommended version of the API and see if it appears on my computer.
Since, the first time I used your mod, it displays the image where I though the stars were "sharper"

**Comment by Abastro** [comment] 2016-06-30 17:13
There will be config option for you, to control fuzziness of stars.

**Comment by PitchBright** [comment] 2016-06-30 17:14
No worries, can you close this issue, I'm preparing a Feature Request issue for sharpness control.

Edit: Unless you want to leave this one open instead, @Abastro ?

**Comment by Abastro** [comment] 2016-06-30 17:19
Discussions about this feature request should have to be continued on #70, with **clearer descriptions**.
+ Note that these kind of issue is categorized as 'Suggestions' and 'Enhancement',
Since it is about visual effect. (Yes, Not a bug)

**Closed by Abastro** 2016-06-30 17:19 UTC
Labels: cosmetic, enhancement, question, suggestion
