### ISSUE TITLE
Slow chunk loading

### ISSUE THREAD

**Issue by Dinocanid** [Abastro/StellarSky#74] opened 2016-08-05 18:48 UTC
I recently added StellarSky and StellarAPI to my game, but had to remove them because it would cause extremely slow chunk loading. I allocated 3G to minecraft after installing and the chunks were still loading slowly. After removing the mods, everything loaded faster again.

minecraft version 1.10.2/ Stellar Sky v0.5.5.1.7/ Stellar API v0.5.4.1/ Forge 1.10.2-12.18.1.2045

**Comment by Abastro** [comment] 2016-08-06 14:47
It's rather problem of CPU than RAM.
Would you profile the performance?

**Comment by Dinocanid** [comment] 2016-08-06 17:01
![2016-08-06_12 57 53](https://cloud.githubusercontent.com/assets/20864790/17458062/9f229eae-5bd5-11e6-8fe0-e762ee6dc0f8.png)
Like this? I have other mods installed too, but they don't cause performance issues for me.

**Comment by Abastro** [comment] 2016-08-07 12:14
What is needed here is something like VisualVM CPU Profiling. Would you do that?

**Comment by Dinocanid** [comment] 2016-08-08 00:12
I've never done it before. I can download VisualVM, but which .jar would I use?

**Comment by Abastro** [comment] 2016-08-09 03:03
There will be executable file in bin folder. Run it, and Run Minecraft in normal way with the mods.
Then the Minecraft will be shown as '....launchwrapper...' in Application tree on the left side.
Double-Click it, and select 'Sampler' tab. Click CPU button there, play in Minecraft for a while.
After that, take a snapshot by clicking 'Snapshot' button.
Finally, click 'Export to...' button which is shaped like save button. Post the exported file here.

**Comment by dexman545** [comment] 2016-08-11 00:13
I've also noticed this issue, and have profiled it: http://www.mediafire.com/download/pcip23txhk24bxf/profile.nps
it should also be noted that this was/is experienced in 1.7.10

Also, if you're still interested in FPS performance hit with Stellar Sky, pre-stellar is ~350, post is ~86
(should be noted that other mods are installed)

**Comment by Abastro** [comment] 2016-08-11 14:21
There will be no solution for this, it's nearly impossible to optimize in this case.
Set Mag_Limit to smaller value, 4.0~5.0 will be reasonable. (This makes only bright stars will be able to be seen)
If this fixes this issue, please close this one. I'll consider decreasing the default mag limit on the next update.

**Comment by dexman545** [comment] 2016-08-11 18:45
Decreasing mag limit to 5 gave a noticeable increase in chunk loading over mag limit 6, still slow, but much more playable.

**Comment by Abastro** [comment] 2017-07-18 05:59
Actually this is duplicate of #64.

**Closed as completed by Abastro** 2017-07-18 05:59 UTC
Labels: fps
